#pragma once

static AutoPattern tutorialPattern[] =
{
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "Welcome to the\nCandy Crisis\ntutorial!" },
	{ .command = kIdleTicks,      .d1 = 180, .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "I'll be your guide\nthroughout the\ntutorial. Let's\nget started!" },
	{ .command = kRetrieve,       .d1 = 1,   .d2 = 1,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 240, .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "When you start the\ngame, you'll find a\npair of candies\nfalling from the sky." },
	{ .command = kIdleTicks,      .d1 = 240, .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "Your goal is to\nkeep these candies\nfrom overflowing the\nboard!" },
	{ .command = kBlockUntilLand, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 2,   .d2 = 2,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 60,  .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "You control the\ncandy by moving\nthem left and right." },
	{ .command = kIdleTicks,      .d1 = 120, .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 120, .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "Press '~~'\nto make the pieces\nmove left." },
	{ .command = kRetrieve,       .d1 = 3,   .d2 = 3,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 60,  .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 90,  .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "Use '||' to\nmake the pieces\nmove right." },
	{ .command = kIdleTicks,      .d1 = 180, .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "You can also\nmake the pieces\nrotate around each\nother." },
	{ .command = kRetrieve,       .d1 = 4,   .d2 = 3,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 180, .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "Press '{{'\nto make the pieces\nrotate." },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "Also, '``'\ncauses the candy\nto drop faster." },
	{ .command = kIdleTicks,      .d1 = 180, .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "To pause the game\nor adjust settings,\npress 'esc.'" },
	{ .command = kIdleTicks,      .d1 = 280, .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "The candy in\nthis game is made\nfrom a highly\nunstable substance!" },
	{ .command = kRetrieve,       .d1 = 2,   .d2 = 2,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 200, .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "So when four\npieces of the same\ncolor come into\ncontact..." },
	{ .command = kPosition,       .d1 = 1,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 180, .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "... they vaporize!" },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 60,  .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "Let's see that\nonce again." },
	{ .command = kRetrieve,       .d1 = 1,   .d2 = 1,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 120, .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "Pop!" },
	{ .command = kIdleTicks,      .d1 = 120, .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "You can even get\nfive or more\npieces to pop\nall at the same\ntime!" },
	{ .command = kRetrieve,       .d1 = 4,   .d2 = 4,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 4,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 4,   .d2 = 4,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 3,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 4,   .d2 = 4,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 4,   .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "Pop!\n\nTechniques like this\ncan earn lots of\nbonus points." },
	{ .command = kIdleTicks,      .d1 = 180, .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "You can also pop\nmore than one color\nat once." },
	{ .command = kRetrieve,       .d1 = 5,   .d2 = 5,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 4,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 6,   .d2 = 5,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 3,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 3,   .d2 = 5,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 10,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 10,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "All right!" },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 0,   .d2 = 6,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "You can even set\nup devastating\nchain reactions..." },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 0,   .d2 = 6,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 90,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 6,   .d2 = 6,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 60,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 1,   .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "... like this!" },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "Tricky, isn't it?" },
	{ .command = kRetrieve,       .d1 = 1,   .d2 = 2,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 60,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 1,   .d2 = 2,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 60,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 3,   .d2 = 1,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 60,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 3,   .d2 = 2,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 3,   .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "Let's see one more\nexample of a chain\nreaction." },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 1,   .d2 = 2,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 60,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 5,   .d2 = 5,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 1,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 5,   .d2 = 3,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 10,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 10,  .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 1,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 3,   .d2 = 5,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 10,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 3,   .d2 = 3,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 20,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 90,  .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "There's one more\nthing you need to\nknow about..." },
	{ .command = kIdleTicks,      .d1 = 180, .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "Watch out for the\nsee-through candy!" },
	{ .command = kIdleTicks,      .d1 = 60,  .d2 = 0,   .message = NULL },
	{ .command = kPunish,         .d1 = 18,  .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 1,   .d2 = 1,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 120, .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 20,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "When your opponent\nvaporizes a group of\ncandies, they also\nsend some transparent\npieces to you!" },
	{ .command = kRetrieve,       .d1 = 1,   .d2 = 1,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 90,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 4,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 30,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 1,   .d2 = 1,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 60,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 90,  .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "You can get rid of\nthese pieces by\nvaporizing something\nnext to them." },
	{ .command = kIdleTicks,      .d1 = 150, .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 60,  .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 1,   .d2 = 2,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "There are also\nsome bonus items\nwhich can come\nin handy." },
	{ .command = kIdleTicks,      .d1 = 20,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 20,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 3,   .d2 = 1,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 20,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 10,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 10,  .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 20,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 1,   .d2 = 3,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 10,  .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 1,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 15,  .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "One of these bonus\nitems is the Crazy\nCandy!" },
	{ .command = kRetrieve,       .d1 = -1,  .d2 = 2,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 15,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 10,  .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 100, .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "The Crazy Candy\ntakes on the\ncolor of one of\nits neighbors." },
	{ .command = kIdleTicks,      .d1 = 60,  .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 3,   .d2 = 4,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 4,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 1,   .d2 = 5,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 1,   .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "Another useful bonus\nitem is the bomb!" },
	{ .command = kRetrieve,       .d1 = 2,   .d2 = 3,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 0,   .d2 = 3,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 3,   .d2 = 2,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 4,   .d2 = 3,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 3,   .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve,       .d1 = 2,   .d2 = 3,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kSpin,           .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 5,   .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kRetrieve, .d1 = kBombBottom, .d2 = kBombTop, .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "When the bomb lands\non one color\nof candy, all\npieces of that\ncolor will\nvaporize!" },
	{ .command = kIdleTicks,      .d1 = 100, .d2 = 0,   .message = NULL },
	{ .command = kPosition,       .d1 = 4,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 120, .d2 = 0,   .message = NULL },
	{ .command = kBlockUntilDrop, .d1 = 0,   .d2 = 0,   .message = NULL },
	{ .command = kIdleTicks,      .d1 = 200, .d2 = 0,   .message = NULL },
	{ .command = kMessage,        .d1 = 0,   .d2 = 0,   .message = "Now you're ready\nto play Candy Crisis.\nGood luck!" },
	{ .command = kIdleTicks,      .d1 = 270, .d2 = 0,   .message = NULL },

	{ .command = kComplete,       .d1 = 0,   .d2 = 0,   .message = NULL }
};
